### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by voiduwu** [codingwolves/furry.js#2]
My only question is "why?".
This is a barely modified fork of discord.js (based off of number and quality of commits) so why fork it in the first place when you could've used the original library itself? If it was to fix bugs and add custom snippets of code for personal use, I understand, but I didn't see much of that looking through your commit history.

**Comment by codepupper** [comment]
Do you do this on all d.js forks or only on mine? If only on then why? I use normal d.js. This is just for shits and giggles.  But Jfc let people fork what the fuck they want.
